services:
  oi-app:
    container_name: oi-app
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    tty: true
    networks:
      - sail

  localtunnel:
    image: efrecon/localtunnel
    restart: on-failure
    command:
        --local-host web --port 80 --subdomain ${LOCALTUNNEL_SUBDOMAIN}
    depends_on:
        - web
        - oi-app
    networks:
        - sail
  
networks:
  sail:
    driver: bridge
